"""Cursor IDE rule file template (.cursor/rules/chowkidar-alerts.mdc)."""

from __future__ import annotations

from datetime import datetime, timezone


def generate_cursor_rules(deprecations: list[dict]) -> str:
    """Generate a .mdc rules file for Cursor with usage-aware advisory details."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    globs = '["**/.env*", "**/config.*", "**/settings.*", "**/constants.*", "**/*.py", "**/*.js", "**/*.ts"]'
    header = f"""---
description: "Chowkidar — LLM model deprecation and smart advisory alerts"
globs: {globs}
alwaysApply: false
---

## LLM Model Deprecation Alerts (auto-generated by Chowkidar)

The following models in this project are deprecated or sunsetting.
**When editing files containing these model strings, migrate them to the recommended replacements.**

"""

    table = _build_table(deprecations)
    advisory = _build_advisory_section(deprecations)

    footer = f"""
---
*Last updated: {now} by [Chowkidar](https://github.com/chowkidar) (Local-first watchdog).*
*Do not edit this file manually — it is regenerated automatically.*
"""

    return header + table + advisory + footer


def _build_table(deprecations: list[dict]) -> str:
    lines = ["| Variable | File | Current Model | Sunset Date | Replacement Recommendation | Confidence | Breaking? |"]
    lines.append("|---|---|---|---|---|---|---|")

    for dep in deprecations:
        file_short = dep.get("file", "").split("/")[-1]
        
        # Prefer smart recommended model over raw replacement ID
        rec = dep.get("recommended_model")
        if not rec and dep.get("replacement"):
            rec = dep.get("replacement").split("/")[-1]
        replacement = rec or "check provider docs"
        
        confidence = dep.get("replacement_confidence") or dep.get("confidence") or "medium"
        breaking = "Yes" if dep.get("breaking_changes") else "No"
        days = dep.get("days_until", "?")
        sunset = dep.get("sunset_date", "unknown")

        if isinstance(days, int) and days <= 0:
            sunset = f"**{sunset} (PASSED)**"
        elif isinstance(days, int) and days <= 7:
            sunset = f"**{sunset} ({days}d left)**"
        elif isinstance(days, int):
            sunset = f"{sunset} ({days}d left)"

        lines.append(
            f"| `{dep.get('variable', '?')}` "
            f"| `{file_short}` "
            f"| `{dep.get('model', '?')}` "
            f"| {sunset} "
            f"| `{replacement}` "
            f"| {confidence} "
            f"| {breaking} |"
        )

    return "\n".join(lines)


def _build_advisory_section(deprecations: list[dict]) -> str:
    sections = ["\n\n### LLM Usage Advisory & Migration Details\n"]
    
    for dep in deprecations:
        var = dep.get("variable", "?")
        model = dep.get("model", "?")
        purpose = dep.get("purpose") or "general-purpose model usage"
        rec = dep.get("recommended_model")
        if not rec and dep.get("replacement"):
            rec = dep.get("replacement").split("/")[-1]
        replacement = rec or "check provider docs"
        
        reason = dep.get("reason") or "Standard capability-matched upgrade path suggested by registry."
        risk = dep.get("risk") or "Review and test before deployment."

        sections.append(f"""#### Variable: `{var}` (Model: `{model}`)
- **Inferred Purpose**: {purpose}
- **Recommended Successor**: `{replacement}`
- **Reason**: {reason}
- **Risk Assessment**: {risk}
- **Migration Assistant Instruction**:
  > "Please migrate variable `{var}` in this project from `{model}` to `{replacement}`. Review configuration references to ensure the replacement model operates as expected."
""")
    return "\n".join(sections)
