"""Windsurf rules template (.windsurfrules)."""

from __future__ import annotations

from datetime import datetime, timezone

MARKER_START = "# --- chowkidar:start ---"
MARKER_END = "# --- chowkidar:end ---"


def generate_windsurf_section(deprecations: list[dict]) -> str:
    """Generate the Chowkidar section for .windsurfrules with advisory details."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    lines = [
        MARKER_START,
        "",
        "## Chowkidar — LLM Model Deprecation & Smart Advisory Alerts",
        "",
        "The following LLM models in this project are deprecated or sunsetting.",
        "When modifying files referencing these models, update them to the replacements.",
        "",
    ]

    for dep in deprecations:
        file_short = dep.get("file", "").split("/")[-1]
        
        rec = dep.get("recommended_model")
        if not rec and dep.get("replacement"):
            rec = dep.get("replacement").split("/")[-1]
        replacement = rec or "check provider docs"
        
        days = dep.get("days_until", "?")
        sunset = dep.get("sunset_date", "unknown")

        urgency = ""
        if isinstance(days, int) and days <= 0:
            urgency = " [SUNSET PASSED]"
        elif isinstance(days, int) and days <= 7:
            urgency = f" [{days}d left]"

        lines.append(
            f"- {dep.get('model', '?')} in {file_short} ({dep.get('variable', '?')}): "
            f"Sunset {sunset}{urgency}. Use {replacement} instead."
        )

    lines.append("\n### LLM Usage Advisory & Migration Details\n")
    for dep in deprecations:
        var = dep.get("variable", "?")
        model = dep.get("model", "?")
        purpose = dep.get("purpose") or "general-purpose model usage"
        
        rec = dep.get("recommended_model")
        if not rec and dep.get("replacement"):
            rec = dep.get("replacement").split("/")[-1]
        replacement = rec or "check provider docs"
        
        reason = dep.get("reason") or "Standard capability-matched upgrade path suggested by registry."
        risk = dep.get("risk") or "Review and test before deployment."

        lines.append(f"#### Variable: `{var}` (Model: `{model}`)\n"
                     f"- **Inferred Purpose**: {purpose}\n"
                     f"- **Recommended Successor**: `{replacement}`\n"
                     f"- **Reason**: {reason}\n"
                     f"- **Risk Assessment**: {risk}\n"
                     f"- **Migration Assistant Instruction**:\n"
                     f"  > \"Please migrate variable `{var}` in this project from `{model}` to `{replacement}`. Review configuration references to ensure the replacement model operates as expected.\"\n")

    lines.extend([
        "",
        f"# Auto-generated by Chowkidar on {now} (Local-first watchdog). Do not edit this section manually.",
        "",
        MARKER_END,
    ])

    return "\n".join(lines)


def inject_into_windsurf_file(existing_content: str, new_section: str) -> str:
    """Insert or replace the Chowkidar section in .windsurfrules."""
    if MARKER_START in existing_content:
        before = existing_content.split(MARKER_START)[0].rstrip()
        after_parts = existing_content.split(MARKER_END)
        after = after_parts[1].lstrip() if len(after_parts) > 1 else ""
        return f"{before}\n\n{new_section}\n\n{after}".strip() + "\n"
    else:
        if existing_content.strip():
            return f"{existing_content.rstrip()}\n\n{new_section}\n"
        return new_section + "\n"
